### ISSUE TITLE
Feature: Use one request to get lots of information

### ISSUE THREAD

**Issue by LordMike** [dave-code-ruiz/uhomeuponor#1]
Hi,

I've been reading the code a bit, and I think it's possible to reduce the number of API calls the code makes. As I read it, `Uhome` will make `14 + 11 * controllers + 23 * thermostats` - which for me, at 2 controllers & 10 thermostats is 266 API calls.

I've just acquired a U@Home (R-167) and have tried making a call against it with two object requests instead of one. In the screenshots below (from fiddler), we can see the two responses come back. This should be expandable to all the objects and properties needed, so that `Uhome.update()` can become a three-call method.

![image](https://user-images.githubusercontent.com/1027111/72761944-fc9a4000-3bdd-11ea-9034-3b4a51eaa8e9.png)

![image](https://user-images.githubusercontent.com/1027111/72761946-00c65d80-3bde-11ea-909f-3734fabad1ad.png)

Would an update like this be welcome?

**Comment by dave-code-ruiz** [comment]
Thanks a lot for your info.
I know my code make a lot of API calls, but i dont know how can i reduce it.
I try a change in my code with your info and work great!
When i develop it for all objects i upload it.
Thanks a lot.

**Comment by dave-code-ruiz** [comment]
Solved, thks @LordMike

**Comment by LordMike** [comment]
I see that you're doing a lot of JSON stuff manually. Wouldn't it make sense to build the JSON documents using the same JSON library you're parsing responses with?
