### ISSUE TITLE
Possible issue: thermostats not updating

### ISSUE THREAD

**Issue by LordMike** [dave-code-ruiz/uhomeuponor#17]
I noticed this morning that my thermostats weren’t updating their values. 

Just an FYI in case you see the same. 

I’ll get a look at this when I get home.

**Comment by dave-code-ruiz** [comment]
I have similar problem long time ago. I see in graph a straight line because updating values not work.

I solved it temporaly restarting gateway

**Comment by LordMike** [comment]
That's odd.. I wonder if there's a logical flaw in the updater.

Will take a look at it.

**Comment by jptuomi** [comment]
I noticed this weekend that the values had stopped updating in HomeAssistant.
Although also when logging in to the app and smatrixapp.uponor.com.

For me it happened at 2020-02-06 13:30 GMT, could it be a firmware update or similar for the gateway?

I didn’t think about doing anything about it but your tip to restart which solved it, I have no info on the firmware versions before or after.

Best Regards
Johan Tuomi

**Comment by LordMike** [comment]
I rebooted my gateway too, and voila. The "Server" diode on the gateway wasn't on, but was after the reboot.. Maybe it crashed? :|

**Comment by jptuomi** [comment]
It should be mentioned that I’m still on the version that was quite stale before mike got involved.
So it can’t be because of the new changes at least, would like to think that I experienced it way before I got into HomeAssistant as well – can’t say for sure though.
Because lack of time as a parent etc etc…

**Comment by LordMike** [comment]
I haven't re-observed this after rebooting the gateway. The next time it happens, I'll try to identify if the gateway can be seen as down, via. the API.. and if so report on that instead.. (Maybe a sensor for the gateway itself).

**Comment by dave-code-ruiz** [comment]
I re-observed this error, and in my log file have this warning, many times:

feb 12 16:40:15 hassbian hass[561]: 2020-02-12 16:40:15 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.uhome_humidity_1_4_bano is taking over 10 seconds
feb 12 16:40:32 hassbian hass[561]: 2020-02-12 16:40:32 WARNING (MainThread) [homeassistant.components.sensor] Updating uhomeuponor sensor took longer than the scheduled update interval 0:00:30

I think is not enough information for re-open issue, but post information anyway.

**Comment by LordMike** [comment]
This sounds like the server has gone away.. I did observe that the gateway was unreliable. Just pining it once every second had a few dropped packets every once in a while.

**Comment by LordMike** [comment]
It crashed again. I dumped all objects, all properties (up to 5.000 - it seems properties go to 1.000), and I can't find a clear-cut value that indicates the U@Home device has lost connection to the thermostats.
