### ISSUE TITLE
Feature: Expose this in HACS

### ISSUE THREAD

**Issue by LordMike** [dave-code-ruiz/uhomeuponor#2]
https://hacs.xyz/docs/publish/start

Requirements:

* Add `hacs.json`
* OPTIONAL add `info.md`
* Submit MR to [this repo](https://github.com/hacs/default)

Looks like `hacs.json` just has to be:
```json
{
  "name": "Uhome",
  "render_readme": true,
  "domains": ["sensor", "climate"]
}
```

**Comment by dave-code-ruiz** [comment]
I try to expose in HACS, i think i do all steps correct

i waiting for a response

**Comment by LordMike** [comment]
I think you need to add a PR here, https://github.com/hacs/default/pulls.

In any case. It can be tested now, by adding the repo in HACS (on an HA server). Can be used to test.

**Comment by LordMike** [comment]
~~I just tried adding the repo & installing the integration via. HACS, it didn't work. At least not with my current configuration.~~

EDIT: Scratch that. Bad test. It works.

**Comment by LordMike** [comment]
I've added a PR that updates the docs, and adds the necessary `hacs.json` file. I cannot add a PR towards the default repos, as I'm not an Owner of this repository. So to complete this, @dave-code-ruiz can do the PR instead of me.

**Comment by dave-code-ruiz** [comment]
> Agregué un RP que actualiza los documentos y agrega el `hacs.json`archivo necesario . No puedo agregar un RP hacia los repositorios predeterminados, ya que no soy propietario de este repositorio. Para completar esto, @ dave-code-ruiz puede hacer el PR en lugar de mí.

Sorry for taking so long

https://github.com/hacs/default/pull/225

I do it now

Can you review why checks fail in .github file? Thnks

https://github.com/hacs/default/pull/225/checks?check_run_id=442987957

**Comment by LordMike** [comment]
Yeap, you're missing a comma, "," after your text in the integrations file.

**Comment by dave-code-ruiz** [comment]
incredible, my mind is getting worse

thnks
