### ISSUE TITLE
uhomeuponor: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 

### ISSUE THREAD

**Issue by LordMike** [dave-code-ruiz/uhomeuponor#22]
Reported in `HASS 0.109`

> uhomeuponor: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this

**Comment by dave-code-ruiz** [comment]
we have not translations folder
