### ISSUE TITLE
Warning: No 'version' key in the manifest file for custom integration 'uhomeuponor'

### ISSUE THREAD

**Issue by zkiifreak** [dave-code-ruiz/uhomeuponor#27]
WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'uhomeuponor'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'uhomeuponor'.
This error comes at start-up of Home Assistant.
Has this been taken care of? Or is my version so old?

**Comment by dave-code-ruiz** [comment]
Try now,

I update manifest file

**Comment by zkiifreak** [comment]
Seems to have done the trick 👍👍
