### ISSUE TITLE
Loosing communication with U@home

### ISSUE THREAD

**Issue by mrwee** [dave-code-ruiz/uhomeuponor#29]
I very often get errors like
`2022-05-03 18:13:29 WARNING (MainThread) [homeassistant.components.climate] Updating uhomeuponor climate took longer than the scheduled update interval 0:01:00`

`2022-05-03 18:13:39 WARNING (MainThread) [homeassistant.components.sensor] Updating uhomeuponor sensor took longer than the scheduled update interval 0:00:30`

after that hass receives no updates from the Uponor sensors. Restarting Hass fixes the problem.

I can browse+ping my U@home with no issues
Running Home Assistant 2022.4.7

**Comment by dave-code-ruiz** [comment]
Hi, thnks for your report and send useful information.

I have same problem (sensor graphics shows a straight line) but only happens once in a while.

I needed more information, please change to debug mode and try to locate this messages in logs:

"The thermostat temperature sensor '%s' had invalid data"
"Uponor thermostat temperature sensor was unable to update: %s"

These are displayed when updating sensor.

Other useful information is how many times does it happen

When component don´t work , try to change temperature in climate, i think it is work and only fail update sensor/climate 

On the other hand, i was developing the configure flow for this component and when it's finished it is posible reload component without reboot HA

**Comment by mrwee** [comment]
Hi,

Can you please assist me in, how to enable debug information?

**Comment by dave-code-ruiz** [comment]
Hi,
I upload new version, you now can "reload" integration if you have any problem, 
keep me inquired to issue status
regards,

**Comment by dave-code-ruiz** [comment]
I verified it, When I loosing communication i use "reload" command in integration and it solved problem

**Comment by mrwee** [comment]
Save here. No update for 2 days, hitting reload brought updates back. Is this issue fixable? Do you need more data?

**Comment by dave-code-ruiz** [comment]
If i find out the cause of the issue, reopen it and try to solved if definitely, 

You can activate debug mode in configuration.yaml

```

logger:
  default: info
  logs:
    custom_components.uhomeuponor: debug

```

If you see something important thing in logs when loss communication, please send me it
