### ISSUE TITLE
climate entities stops working, rest are fine

### ISSUE THREAD

**Issue by mrwee** [dave-code-ruiz/uhomeuponor#32]
After a while I see all my climate entities stop working, the rest are working fine. Rebooting Hass does not solve it.
![image](https://user-images.githubusercontent.com/6720774/199738777-eb45e14f-b544-461c-9111-96c69ea5a9d7.png)

Running on:
 Home Assistant 2022.10.5
 Supervisor 2022.10.0
 Operating System 9.3
 Frontend 20221010.0 - latest

**Comment by dave-code-ruiz** [comment]
Try to delete integration "Uhome Uponor" and re-add it

**Comment by mrwee** [comment]
That helped. Somehow my U@home looses the zone names I've put into it, I think that's what the integration didn't like.

**Comment by dave-code-ruiz** [comment]
Yes, sometimes U@home do stranger things, ;) , you can reload integration or delete integration and re-add it for reload zone names. 
Homeassistant create entities with this names, and it is needed reload for get new names
