### ISSUE TITLE
Failed to call service climate/set_temperature

### ISSUE THREAD

**Issue by mtnezdilarduya** [dave-code-ruiz/uhomeuponor#34]
Hi, I'm getting the following error when trying to change target temperature in any climate entity

Failed to call service climate/set_temperature. Detected that custom integration 'uhomeuponor' calls async_create_task from a thread at custom_components/uhomeuponor/uponor_api/__init__.py, line 271: self.hass.async_create_task(self.do_rest_call(req)). Please report it to the author of the 'uhomeuponor' custom integration.

Uponor Hw: r167
integration version 1.3.1

**Comment by tobyt99** [comment]
@dave-code-ruiz apologies for being slow but how do I "use sync methods"?  is there something I need to change?

**Comment by dave-code-ruiz** [comment]
I dont undertand your question, you refer to "async" methods, this information is used inside the integration, it is transparent for final user, you only need to udpate version of integration to 1.3.2 or upper
