### ISSUE TITLE
Feature: Battery indicator

### ISSUE THREAD

**Issue by LordMike** [dave-code-ruiz/uhomeuponor#5]
I've noticed there's a property named `battery_alarm`, at address `101`. It currently has no value on any of my thermostats, but I'm thinking it'll get one when they're about to run out.

We could add an attribute for battery, on the `climate.*` entities - or perhaps somewhere else.

**Comment by fcastroruiz** [comment]
Solved

**Comment by LordMike** [comment]
You found out how battery alarm operates?

**Comment by dave-code-ruiz** [comment]
> You found out how battery alarm operates?

I dont find nothing about battery operates, i think is an alarm on/off with values 0 / 1 , there are 3 thermostats alarm and 2 general alarms

I see who operates alarm in the official app uponor Smatrix app

if you see it work differently , please reopen issue. thnks
