### ISSUE TITLE
Skip bogus values; when thermostats go offline

### ISSUE THREAD

**Issue by LordMike** [dave-code-ruiz/uhomeuponor#9]
I think my system lost contact with all thermostats for a while. In this picture, all thermostats go to 65535 *C, which iirc is the value of a non-existent thermostat.

Would it make sense to skip bogus values, and simply not report it? Or perhaps register an attribute for "present: yes" when values are fetched, and "present: no" when values are bogus?

![image](https://user-images.githubusercontent.com/1027111/73690505-ccb86580-46d0-11ea-95aa-99a62f9793fe.png)

**Comment by jptuomi** [comment]
Yes please!
I mainly use this addon for monitoring temperatures over time and these values bork up the graphs.
I’m not up to date on the HomeAssistant API but the way HomeAssistant behaves on other implementations is that if there is nothing to be reported it will just seem as the sensor / device isn’t there at that point in time. 

Best regards
Johan Tuomi

**Comment by LordMike** [comment]
Maybe the device should be reported as unavailable, when it misses updates?

If we set the `state` to unavailable, it looks like this:

![image](https://user-images.githubusercontent.com/1027111/73791637-fc37a280-47a2-11ea-90f1-3cdc4dee00b4.png)

**Comment by dave-code-ruiz** [comment]
I have the same bug in my thermostats, API have values "min_setpoint" and "max_setpoint", a try to develop option to limit values between max and min setpoint, but when i try to catch values "65535" my code not catch this, i do not know how to do it.
Temporaly i access to sqlite3 database and delete this values.

**Comment by LordMike** [comment]
I'm working on a refactoring of the code to be able to split the API logic from the thermostat/climate/sensor logic. It should allow entirely skipping bogus values, and providing a state ala `unavailable`
